### ISSUE TITLE
Motion detection and tracking

### ISSUE THREAD

**Issue by adityagandhamal** [Python-World/Python_and_the_Web#313]
# Description

To write a Python script which detects motion of people moving in a videoframe and tracks their movement.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by adityagandhamal** [comment]
I would like to work on this one. Please assign me the task.
